### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by peckjon** [sbt/sbt-concat#29]
Getting an odd casting error on up-do-date pyFASST while attempting some blind source separation... have tried reinstalling numpy and scikits.audiolab to no avail:

Python 2.7.13 :: Anaconda 4.3.0 (x86_64)
numpy 1.13.0
scikits.audiolab 0.11.0
pyFASST 0.9.3

`pip install -U numpy scikits.audiolab pyfasst`

```
import pyfasst.audioModel as am
model = am.MultiChanNMFInst_FASST(audio='stereo.wav',nbComps=2, nbNMFComps=32, spatial_rank=1,verbose=1, iter_num=50)
```

```
('Computing the chosen signal representation:', 'stft')
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/peckjon/anaconda/lib/python2.7/site-packages/pyfasst/audioModel.py", line 2339, in __init__
    self.comp_transf_Cx()
  File "/Users/peckjon/anaconda/lib/python2.7/site-packages/pyfasst/audioModel.py", line 278, in comp_transf_Cx
    self.tft.computeTransform(self.audioObject.data[:,n],)
  File "/Users/peckjon/anaconda/lib/python2.7/site-packages/pyfasst/tftransforms/stft.py", line 382, in computeTransform
    fs=self.fs, nfft=self.ftlen
  File "/Users/peckjon/anaconda/lib/python2.7/site-packages/pyfasst/tftransforms/stft.py", line 47, in stft
    data = np.concatenate((np.zeros(lengthWindow/2.0), data))
TypeError: 'float' object cannot be interpreted as an index
```

I can resolve the error by casting lengthWindow to int and changing the offending line to `np.zeros(lengthWindow/2)` (plus a few similar lines later on), but this results in empty output files, so clearly I'm missing something... (among others, why would one ever attempt to use a float as a parameter to `np.zeros`!?)

**Comment by jroper** [comment]
I think you've got the wrong project, this is sbt-concat, which is an sbt plugin written in Scala to concatenate javascript/css files. This project has absolutely nothing to do with python, numpy or pyfasst.
